### ISSUE TITLE
Some spelling issues and other stuff

### ISSUE THREAD

**Issue by Kakadu** [ocsigen/tuto#1]
From http://ocsigen.org/tuto/manual/tutowidgets

1. It will be great to have some clickable anchors to create URLs which point to specific step of the tutorial. Some other pages in ocsigen website have these anchors
2. 2nd step:  Elim_content -> Eliom_content
3. 2nd step: To_dom -> Eliom_content.Html.To_dom
4. Many tutorials have just `tuto` in the title of the tab. It would be great to have actual tutorial title there.

http://ocsigen.org/tuto/6.1/manual/reactivemediaplayer#frp_medial_player

1. Functionnal  -> Functional
2. ΗΤΜΛ ? Why lambda?

Added: 15.03.2018

On page  https://ocsigen.org/eliom/6.2/manual/server-params#any you still use old camlp4 syntax like 
`<< <strong>($str:a$, $str:s$)</strong> >>`. AFAIR it is not supported these days.

**Comment by balat** [comment]
Thank you! I think everything is now fixed, at least in dev versions which will be released very soon. Closing this.
