### ISSUE TITLE
code following tutoreact does not compile

### ISSUE THREAD

**Issue by RuyBlast** [ocsigen/tuto#20]
Hi !
Following tutorial https://github.com/ocsigen/tuto/blob/master/tutos/dev/manual/tutoreact.wiki until line 148, just after replacing main_service_handler of base ocsigen-start by
```
let%server main_service_handler userid_o () () =
  let%lwt content = Tutoreact_messages.display userid_o in
  Tutoreact_container.page userid_o content
```
I got following error:
```
Error: The implementation tutoreact_handlers.eliom
       does not match the interface _client/tutoreact_handlers.cmi:
       The value `main_service_handler' is required but not provided
       File "tutoreact_handlers.eliomi", line 56, characters 0-99:
         Expected declaration
Makefile.os:284: recipe for target '_client/tutoreact_handlers.cmo' failed
make: *** [_client/tutoreact_handlers.cmo] Error 2
```
It seems like tutoreact_handlers.eliomi file is expected main_service_handler declared as %shared, but declaring it as shared also raises an error at compile time (which can be solved invoking ~% but then I got a runtime error with a naive implementation).
How could we fix this ?
Best !

**Comment by rluong89** [comment]
Hello @RuyBlast!

The tutoreact tutorial has been updated, you can see the new version at the following link:
https://ocsigen.org/tuto/dev/manual/tutoreact

Thank you for your feedback, if you plan to give it a new try, don't hesitate to let us know if you find any more problems!
